#include <iostream>
#include <exception>

void foo(void) {
}

int main(void) {
  foo();
  
  return EXIT_SUCCESS;
}
